// Header alias map for DB_PROJECTS legacy CSV — separate from the server
// action file (Next.js forbids non-async-function exports from "use server").

export const PROJECT_HEADER_ALIASES: Record<string, string> = {
	project_id: "project_id",
	invoice_number: "invoice_number",
	client_or_event_name: "client_name",
	client_name: "client_name",
	eventtype: "event_type",
	event_type: "event_type",
	eventdate: "event_date",
	event_date: "event_date",
	setup_time: "setup_time",
	starttime: "start_time",
	start_time: "start_time",
	endtime: "end_time",
	end_time: "end_time",
	sleeve_type: "sleeve_type",
	package_name: "package_name",
	base_price_rp: "base_price",
	base_price: "base_price",
	background_type: "background_type",
	include_flashdisk: "include_flashdisk",
	payment_status: "payment_status",
	payment_due_date: "payment_due_date",
	balance_due: "balance_due",
	paid: "paid",
	discount: "discount",
	gross_up: "gross_up",
	tax: "tax",
	total_price: "total_price",
	crew_assigned_a: "crew_a",
	crew_assigned_b: "crew_b",
	venue: "venue",
	city: "city",
	location_maps_url: "maps_url",
	channel_code: "channel",
	design_status: "design_status",
	design_link: "design_link",
	status_project: "status_project",
	notes: "notes",
};
